release: 0.4.0
near/workspaces-rs pull request #170
Opened 2022-07-20 18:11 UTC by ChaoticTempest

Will do a release after this.

2022-07-20 18:33 UTC, ChaoticTempest commented
hmm, after recent additions, the macOS tests seems to be pretty non-deterministic these days... I'll have to test this later, but it does seem like the instance of macOS GH has is really slow since it takes hours to publish the binaries in nearcore

2022-07-20 20:10 UTC, austinabell approved these changes
Release changes LGTM. Definitely worth looking into if the recent changes have caused the increase in non-deterministic issues so we don't push that to developers

2022-07-20 20:10 UTC, austinabell commented on CHANGELOG.md
> +### Fixed
Should we also indicate that the default sandbox version has changed?

2022-07-21 16:23 UTC, austinabell requested changes
having an issue compiling with near-crypto 0.14 on ubuntu:
```
error[E0599]: no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
  --> /home/austinabell/.cargo/registry/src/github.com-1ecc6299db9ec823/near-crypto-0.14.0/src/test_utils.rs:59:62
   |
59 |                 Signature::ED25519(ed25519_dalek::Signature::from_bytes(&SIG).unwrap())
   |                                                              ^^^^^^^^^^ function or associated item not found in `ed25519_dalek::Signature`
```

looking through docs the method doesn't exist, so not sure where this is referenced. Potentially missing a feature?

2022-07-21 16:27 UTC, austinabell approved these changes
nvm seems to be some dep mismatch, removing lockfile cleared

2022-07-21 16:55 UTC, ChaoticTempest commented
disabling the macos-latest test target since we can resolve that later

2022-07-21 19:57 UTC, merged