fix: improve error msg on calling `json` on void function
near/workspaces-rs pull request #286
Opened 2023-08-07 10:06 UTC by shariffdev

Addresses: https://github.com/near/workspaces-rs/issues/278

The error returned on calling `json()` after execution of a void function is:
```
Error: DataConversion

Caused by:
    EOF while parsing a value at line 1 column 0
```

The change proposed gives more context to the error as such:
```
Error: DataConversion

Caused by:
    the Value from ExecutionOutcome is zero bytes
```

2023-08-11 14:56 UTC, shariffdev commented
@frol This PR is ready to be reviewed

2023-08-21 22:02 UTC, frol requested changes

2023-08-21 22:02 UTC, frol commented on workspaces/src/result.rs
> +                        .custom("the Value from ExecutionOutcome is zero bytes"));
I suggest a more clear error message:

```suggestion
                        .custom("the function call returned an empty value, which cannot be parsed as JSON"));
```

2023-09-09 09:01 UTC, frol approved these changes

2023-09-09 09:13 UTC, merged