chore/delete-account-test
near/workspaces-rs pull request #289
Opened 2023-08-21 06:13 UTC by shariffdev

Addresses TODO: https://github.com/near/workspaces-rs/blob/cda1dc4e481e91bb17d95053b42d3b584cf2a95b/workspaces/src/rpc/client.rs#L259

The PR adds a test case for the `delete_account ` rpc method.

2023-08-22 03:35 UTC, shariffdev commented
@frol This is ready to be reviewed

2023-09-09 09:37 UTC, frol requested changes

2023-09-09 09:37 UTC, frol commented on workspaces/tests/account.rs
> +    assert!(bob.view_account().await?.balance > 100 * 1_900_000_000_000_000_000_000_000,);
Also, add assert on that alice account does not exist anymore

2023-09-09 10:32 UTC, frol commented
@shariffdev Please, resolve the merge conflict.

2023-09-09 10:33 UTC, frol approved these changes

2023-09-09 12:39 UTC, merged