chore/transfer-near-test
near/workspaces-rs pull request #290
Opened 2023-08-21 06:37 UTC by shariffdev

Addresses TODO: https://github.com/near/workspaces-rs/blob/cda1dc4e481e91bb17d95053b42d3b584cf2a95b/workspaces/src/rpc/client.rs#L185C1-L185C1

The PR adds a test case for the `transfer-near` rpc method.

2023-08-22 03:35 UTC, shariffdev commented
@frol This is ready to be reviewed

2023-09-09 09:40 UTC, frol requested changes

2023-09-09 09:40 UTC, frol commented on workspaces/tests/account.rs
> +    // transfer 500_000_000 token from alice to bob
Please, add asserts on that alice's balance has changed (one assert before, and one after the transfer)

2023-09-09 10:20 UTC, frol approved these changes

2023-09-09 10:21 UTC, merged